INSERT INTO subscription.plan (id, name, price_month, price_year) VALUES ('6c96381b-5f73-44e8-a64e-a54a59122641', 'Plan 1', 3000, 0);
INSERT INTO subscription.plan (id, name, price_month, price_year) VALUES ('d19d9c53-c05c-4ea5-9692-a2a8f768ed77', 'Plan 2', 5000, 0);
INSERT INTO subscription.plan (id, name, price_month, price_year) VALUES ('f21a90c8-0b3c-4d31-94b9-72be6530f032', 'Plan 3', 7000, 0);
INSERT INTO subscription.plan (id, name, price_month, price_year) VALUES ('ea9c6ab7-bd82-49a4-b1f3-ee1989d70419', 'Plan 4', 9000, 90000);
