---
apiVersion: v1
kind: Service
metadata:
  labels:
    project: cyrulik
    tier: infrastructure
    app: redis
  name: redis
spec:
  ports:
    - name: http
      port: 6379
      targetPort: 6379
  selector:
    project: cyrulik
    tier: infrastructure
    app: redis
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    project: cyrulik
    tier: infrastructure
    app: redis
  name: redis
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        project: cyrulik
        tier: infrastructure
        app: redis
    spec:
      containers:
        - image: redis:4-alpine
          name: redis
          ports:
            - containerPort: 6379
          resources: {}
          envFrom:
            - secretRef:
                name: cyrulik-secrets
      restartPolicy: Always
status: {}
