version: '3.3'

volumes:
  redisdata:
    driver: local

services:

  zipkin-service:
    container_name: zipkin-service
    env_file:
      - .env
    image: openzipkin/zipkin:2.10.1
    environment:
      STORAGE_TYPE: mem
    restart: always
    ports:
      - "${CONFIG_SERVICE_PORT_ZIPKIN}:9411"


  cassandra-account:
    container_name: cassandra-account
    env_file:
      - .env
    image: spotify/cassandra
    ports:
      - "${CONFIG_DATABASE_PORT_ACCOUNT}:9042"


  zookeeper:
    image: wurstmeister/zookeeper
    env_file:
      - .env
    container_name: zookeeper
    restart: always
    ports:
      - "${CONFIG_SERVICE_PORT_ZOOKEEPER}:2181"

  kafka:
    image: wurstmeister/kafka:1.1.0
    env_file:
      - .env
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "${CONFIG_SERVICE_PORT_KAFKA}:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis:4-alpine
    env_file:
      - .env
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "${CONFIG_SERVICE_PORT_REDIS}:6379"
    volumes:
      - redisdata:/data