version: '3.5'
services:

  zipkin-service:
    container_name: zipkin-service
    image: openzipkin/zipkin:2.10.1
    environment:
      STORAGE_TYPE: mem
    restart: always
    ports:
      - "9411:9411"