server:
  port: ${CONFIG_SERVICE_PORT_ACCOUNT}
  servlet:
    context-path: /account

spring:
  data:
    cassandra:
      keyspace-name: account
      contact-points: ${CONFIG_DATABASE_HOST_ACCOUNT}
      port: ${CONFIG_DATABASE_PORT_ACCOUNT}
      schema-action: create_if_not_exists
      cluster-name: database_account
      create-keyspace: true
  kafka:
    consumer:
      topic:
        account: ACCOUNT
  redis:
    host: ${CONFIG_SERVICE_HOST_REDIS}
    port: ${CONFIG_SERVICE_PORT_REDIS}

security:
  oauth2:
    client:
      clientId: account-service
