logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${CONFIG_SERVICE_HOST_REGISTRY}:${CONFIG_SERVICE_PORT_REGISTRY}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 60
    preferIpAddress: true


spring:
  producer:
    bootstrap-servers: kafka:9092