logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${CONFIG_SERVICE_HOST_REGISTRY}:${CONFIG_SERVICE_PORT_REGISTRY}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 60
    preferIpAddress: true


spring:
  kafka:
    bootstrap-servers: ${CONFIG_SERVICE_HOST_KAFKA}:${CONFIG_SERVICE_PORT_KAFKA}


security:
  oauth2:
    resource:
      userInfoUri: http://${CONFIG_SERVICE_HOST_ACCOUNT}:${CONFIG_SERVICE_PORT_ACCOUNT}/accounts/current
